name: Build and Test Master in docker

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '**'

env:
  OPAMROOT: /home/user/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: skhechnev/ocaml-5.1.0-sail

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'true'

      - run: |
            sudo apt-get update -y
            sudo apt-get install autoconf libgmp-dev pkg-config zlib1g-dev z3 graphviz jq -y

      - name: Installing dependencies
        run: |
            opam pin add ./ -n
            opam install . --deps-only --with-test --with-doc

      - name: Building
        run: |
            opam exec -- dune build
            opam exec -- dune build @install
      
      - name: Running tests in release...
        run: |
          opam exec -- dune test --profile=release

      - name: Send coverage report to Coveralls
        if: github.event_name != 'pull_request'
        run: |
          git config --global --add safe.directory /__w/checker/checker
          opam exec -- make coverage
          opam exec -- bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: /tmp/checkercov
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
